server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelreview_user
    username: hotelreview_admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-44588043.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaawe353ijEcRX0y5d7
            client-secret: HpOEK8zZlpo3LWrh7wb90Q8tYH4dAXTqkDgMyYJBuJNvpZiAkW5vbqDkDcQIp6Cx
        provider:
          okta:
            issuer-uri: https://dev-44588043.okta.com/oauth2/default

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelBreaker:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 5
        timeout-duration: 10s

okta:
  oauth2:
    issuer: https://dev-44588043.okta.com/oauth2/default
    audience: api://default