server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelreview_hotel
    username: hotelreview_admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  application:
    name: HOTEL-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

okta:
  oauth2:
    issuer: https://dev-44588043.okta.com/oauth2/default
    audience: api://default